version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "8000:8000"
    command: bash -c "while sleep 1000; do :; done"
    environment:
      - PYTHONUNBUFFERED=1
